### ISSUE TITLE
Add details of LDAP_X_CONNECTING error code to docs

### ISSUE THREAD

**Issue by sshanks-kx** [KxSystems/ldap#104]
LDAP_X_CONNECTING was missing from ldap docs when doc created - see if explaination can be found/added

**Comment by sshanks-kx** [comment]
ref: https://www.openldap.org/lists/openldap-bugs/201503/msg00061.html

**Comment by cmccarthy1** [comment]
Have added this to my review of the docs, outlined in push [here](https://github.com/cmccarthy1/docs/commit/5f662b5e72404c5633dbc488853067551002ae3d).

**Comment by sshanks-kx** [comment]
Added https://github.com/cmccarthy1/docs/pull/20/commits/d350483a0de3ad30961d4f88c10ae2c94a93d070
